<a href="https://colab.research.google.com/github/dipeshkant0/IRIS-FLOWER-CLASSIFICATION/blob/main/IRIS_FLOWER_CLASSIFICATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as mp
iris= load_iris()

In [ ]:
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
df['species']=pd.Categorical.from_codes(iris.target.data,iris.target_names)

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [ ]:
print(pd.factorize(df['species'])[0])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
df['species']=pd.factorize(df['species'])[0]

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [ ]:
x= df.iloc[:,:4]
y=df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt= DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=dt.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cf= confusion_matrix(y_test,y_pred)
asc=accuracy_score(y_test,y_pred)
print(cf)
print(asc)

[[14  0  0]
 [ 0  7  1]
 [ 0  1  7]]
0.9333333333333333


In [ ]:
from sklearn.naive_bayes import CategoricalNB
nb= CategoricalNB()
nb.fit(x_train,y_train)


CategoricalNB()

In [ ]:
y_predict=nb.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cf= confusion_matrix(y_test,y_predict)
asc=accuracy_score(y_test,y_predict)
print(cf)
print(asc)

[[14  0  0]
 [ 0  7  1]
 [ 0  1  7]]
0.9333333333333333


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rd=RandomForestClassifier(n_estimators=1000,random_state=2)
rd.fit(x_train,y_train)
y_pre= rd.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cf= confusion_matrix(y_test,y_pre)
asc=accuracy_score(y_test,y_pre)
print(cf)
print(asc)

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
0.9666666666666667


In [ ]:
from sklearn.svm import SVC
sv=SVC(kernel='rbf',random_state=2)
sv.fit(x_train,y_train)


SVC(random_state=2)

In [ ]:
y_pred1=sv.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report ,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
from sklearn.svm import SVC
sv=SVC(kernel='linear',random_state=2)
sv.fit(x_train,y_train)

SVC(kernel='linear', random_state=2)

In [ ]:
y_pred2=sv.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report ,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
from sklearn.svm import SVC
sv=SVC(kernel='sigmoid',random_state=0)
sv.fit(x_train,y_train)

SVC(kernel='sigmoid', random_state=0)

In [ ]:
y_pred5=sv.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report ,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred5))
print(accuracy_score(y_test,y_pred5))
print(classification_report(y_test,y_pred5))

[[ 0  0 14]
 [ 0  5  3]
 [ 0  8  0]]
0.16666666666666666
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.38      0.62      0.48         8
           2       0.00      0.00      0.00         8

    accuracy                           0.17        30
   macro avg       0.13      0.21      0.16        30
weighted avg       0.10      0.17      0.13        30



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.svm import SVC
sv=SVC(kernel='poly',random_state=0)
sv.fit(x_train,y_train)

SVC(kernel='poly', random_state=0)

In [ ]:
y_pred4=sv.predict(x_test)
y_pred6=sv.predict(x_train)

In [ ]:
from sklearn.metrics import classification_report ,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred4))
print(accuracy_score(y_test,y_pred4))
print(classification_report(y_test,y_pred4))
print(accuracy_score(y_train,y_pred6))
print(confusion_matrix(y_train,y_pred6))

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

0.975
[[36  0  0]
 [ 0 39  3]
 [ 0  0 42]]
